name: phototext
description: "Machine Learning for Text Recognition, Language Identification and On-Device Translation"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.1
  google_mlkit_language_id: ^0.11.0
  google_mlkit_text_recognition: ^0.13.0
  google_mlkit_translation: ^0.11.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  world_countries: ^1.5.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/card-text_recognition_720.png
    - assets/card-language_id_720.png
    - assets/card-translation_720.png
    - assets/Bitcoin_QR.png
    - assets/paypal.png